sudo: false
language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - ghc: 8.6.4
      env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait stack --no-terminal --system-ghc test --only-snapshot

script:
  - stack --no-terminal --system-ghc test --pedantic

env:
  global:
    secure: 1olN1QGLprLp8dPLsT+V4zXUPz/4yawiwh3d7exseOcbxnH0EDbJNlJcX2leDh8pSdj1R3f41S3SepQor6a6ofXdjIx/GZzlfBG8vIK24WMVDJDngkZIIaUrKolpONUXOUHH12J7lhX7mM7aXjNR+9uPkFAV6hW6ePDKOtQzmbCe/sqSeZRa9Ghxq3OM/xbPiJs4BODnI84CciOqpLTBDzFBU/1BwHOLeYL5p87N8BgGmh66sDIWs7TWccpUx4F6Zh8oCqUDUHFEImRkKn46UzWjJZJC41qkPfebMnBMy6HzNH2yJqfMCmwQoKxc36N5h1B6rDeC14syWC57dmv3sK7rtr5HBJuRZvpSEDWixgs9iV25X2o41SvbCz3yaskiq86xJnBGTPxx7fyLYSpgKg3GNVB1EmO+dwc+BN/0A8S1+swyxI1DFqyaxOEPLpZBWYzYv4e90Fn6xPYSuwdgkSD+HMMAtMMfmFl32vZH4BlPuSmipU/XFAREze/YaX89rHVRO20nT5SKOXP6vBoFWov2xxaMGa8IE5C4MGFDMtVSTpPQFQJSTR44y+5MoUfKo1TCOwOS+MLrAN+P8mIXhag120XGBCLq+Zk/gDVDMP2VN5KnTNyH4mFOOulio9sM6ze+NAgmQU7jxPAnfc44aHgRDuLthWXz0KLlD8jznkg=

