name:                cobot
version:             0.1.0.0
github:              "less-wrong/cobot"
license:             BSD3
author:              "Pavel Yakovlev, Bogdan Neterebskii"
maintainer:          "pavel@yakovlev.me"
copyright:           "2018—2019, Less Wrong Bio"
category:            Bio
synopsis:            Computational biology toolkit to collaborate with researchers in constructive protein engineering
description:         Please see the README on GitHub at <https://github.com/less-wrong/cobot#readme>

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiWayIf
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- UndecidableInstances

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- deepseq
- lens
- linear
- megaparsec
- mtl
- template-haskell
- text

library:
  source-dirs: src

benchmarks:
  cobot-bench:
    main:        Main.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-A64m -qb0 -I0 -N -qn4"'
    dependencies:
    - cobot
    - random
    - parallel
    - clock
    - criterion
    default-extensions:
    - OverloadedStrings

tests:
  cobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-A64m -qb0 -I0 -N -qn4"'
    dependencies:
    - cobot
    - hspec
