name:                cobot
version:             0.1.0.0
github:              "less-wrong/cobot"
license:             BSD3
author:              "Pavel Yakovlev, Bogdan Neterebskii"
maintainer:          "pavel@yakovlev.me"
copyright:           "2018—2019, Less Wrong Bio"
category:            Bio
synopsis:            Computational biology toolkit to collaborate with researchers in constructive protein engineering
description:         Please see the README on GitHub at <https://github.com/less-wrong/cobot#readme>

extra-source-files:
- README.md 
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- deepseq
- lens
- linear
- megaparsec
- mtl
- template-haskell
- text

library:
  source-dirs: src
  default-extensions:
    - AllowAmbiguousTypes
    - ConstraintKinds
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - FlexibleContexts
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - MultiWayIf
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - TypeSynonymInstances
    - UndecidableInstances
    
tests:
  cobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cobot
    - hspec
